=== aparten/CPSC5450_GroupProject/backend/app/schema/email_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Parsed Email Schema",
  "type": "object",

  "properties": {
    "email_id": { "type": "string" },
    "fingerprint": { "type": "string" },

    "source": {
      "type": "object",
      "properties": {
        "dataset": { "type": "string" },
        "split": {
          "type": ["string", "null"],
          "enum": ["train", "val", "test", null]
        }
      },
      "required": ["dataset", "split"]
    },

    "headers": {
      "type": "object",
      "properties": {
        "from_address": { "type": "string" },
        "from_display_name": { "type": ["string", "null"] },
        "reply_to": { "type": ["string", "null"] },
        "return_path": { "type": ["string", "null"] },
        "to_address": { "type": ["string", "null"] },
        "subject": { "type": ["string", "null"] },
        "date": {
          "type": ["string", "null"],
          "format": "date-time"
        },
        "message_id": { "type": ["string", "null"] },

        "auth_results": {
          "type": "object",
          "properties": {
            "spf": {
              "type": ["string", "null"],
              "enum": ["pass", "fail", "softfail", "neutral", "none", null]
            },
            "dkim": {
              "type": ["string", "null"],
              "enum": ["pass", "fail", "none", null]
            },
            "dmarc": {
              "type": ["string", "null"],
              "enum": ["pass", "fail", "none", null]
            }
          },
          "required": ["spf", "dkim", "dmarc"]
        }
      },
      "required": [
        "from_address",
        "from_display_name",
        "reply_to",
        "return_path",
        "to_address",
        "subject",
        "date",
        "message_id",
        "auth_results"
      ]
    },

    "body": {
      "type": "object",
      "properties": {
        "has_html": { "type": "boolean" },
        "plain_text": { "type": ["string", "null"] },
        "attachments": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "filename": { "type": "string" },
              "file_ext": { "type": ["string", "null"] }
            },
            "required": ["filename", "file_ext"]
          }
        }
      },
      "required": ["has_html", "plain_text", "attachments"]
    },

    "indicators": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "urls": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "url_actual": { "type": "string" },
              "url_display_text": { "type": ["string", "null"] },
              "domain": { "type": "string" }
            },
            "required": ["url_actual", "url_display_text", "domain"]
          }
        },
        "domains": {
          "type": "array",
          "items": { "type": "string" }
        },
        "ip_addresses": {
          "type": "array",
          "items": { "type": "string" }
        }
      },
      "required": ["urls", "domains", "ip_addresses"]
    },

    "derived_flags": {
      "type": "object",
      "properties": {
        "display_name_mismatch": { "type": "boolean" },
        "sender_domain_mismatch": { "type": "boolean" },
        "lookalike_domain_detected": { "type": "boolean" },
        "internal_impersonation": { "type": "boolean" },
        "unicode_trick_detected": { "type": "boolean" }
      },
      "required": [
        "display_name_mismatch",
        "sender_domain_mismatch",
        "lookalike_domain_detected",
        "internal_impersonation",
        "unicode_trick_detected"
      ]
    },

    "keyword_counts": {
      "type": "object",
      "properties": {
        "urgency": { "type": ["integer", "null"] },
        "credentials": { "type": ["integer", "null"] },
        "payment": { "type": ["integer", "null"] },
        "threat": { "type": ["integer", "null"] }
      },
      "required": ["urgency", "credentials", "payment", "threat"]
    },

    "label": {
      "type": ["string", "null"],
      "enum": ["phishing", "suspicious", "benign", null]
    }
  },

  "required": [
    "email_id",
    "fingerprint",
    "source",
    "headers",
    "body",
    "indicators",
    "derived_flags",
    "keyword_counts",
    "label"
  ]
}

=== aparten/CPSC5450_GroupProject/backend/app/email_data/parsed/9372cb7a-e775-4000-a981-8b46cd134c19.json
{
  "email_id": "9372cb7a-e775-4000-a981-8b46cd134c19",
  "fingerprint": "02645e7705483178d7e785268ef5962b8d8e7bd90f7aac011183ffb10527b9c9",
  "source": {
    "dataset": "unknown",
    "split": null
  },
  "headers": {
    "from_address": "0000019b7122a2be-dmarc-request@RAVEN.UTC.EDU",
    "from_display_name": "Gressel, Brendan",
    "reply_to": "\"Gressel, Brendan\" <brendan-gressel@UTC.EDU>",
    "return_path": "<owner-cse-grad*wjr486**MOCS*-UTC*-EDU@raven.utc.edu>",
    "to_address": "CSE-GRAD@RAVEN.UTC.EDU",
    "subject": "UTC ACM's First Meeting of the Semester!",
    "date": "2026-01-28T15:05:18+00:00",
    "message_id": "<DM3PR02MB1029572F674B17F274E2AFE3CE691A@DM3PR02MB10295.namprd02.prod.outlook.com>",
    "auth_results": {
      "spf": "pass",
      "dkim": null,
      "dmarc": null
    }
  },
  "body": {
    "has_html": true,
    "plain_text": "Hey everyone!\r\nWe\u2019re kicking off the semester with the first UTC ACM meeting, and we\u2019d love to see you there!\r\nWhen: Friday, January 30th, 2026 at 12:00 PM\r\nWhere: ECS Building, Room 321\r\nWe\u2019ll have pizza and a fun icebreaker activity to help everyone meet and connect\u2014so come hungry and ready to hang out!\r\nIt\u2019s a great chance to meet other students interested in computing and get a preview of what ACM has planned for the semester. Whether you\u2019re a returning member or brand new, you\u2019re more than welcome.\r\nJoin our Discord to stay up to date with all club events: https://discord.gg/ssJhudVntc\r\nLet\u2019s start the semester strong.\r\nBest regards,\r\nThe UTC ACM Team\r\n\r\n\r\n########################################################################\r\n\r\nTo unsubscribe from the CSE-GRAD list, click the following link:\r\nhttp://raven.utc.edu/SCRIPTS/WA.EXE?TICKET=NzM5Njc0IHdqcjQ4NkBNT0NTLlVUQy5FRFUgQ1NFLUdSQUQgIMXABQ%2FWx4qE&c=SIGNOFF\r\n",
    "attachments": []
  },
  "indicators": {
    "urls": [
      {
        "url_actual": "https://discord.gg/ssJhudVntc",
        "url_display_text": null,
        "domain": "discord.gg"
      },
      {
        "url_actual": "http://raven.utc.edu/SCRIPTS/WA.EXE?TICKET=NzM5Njc0IHdqcjQ4NkBNT0NTLlVUQy5FRFUgQ1NFLUdSQUQgIMXABQ%2FWx4qE&c=SIGNOFF",
        "url_display_text": null,
        "domain": "utc.edu"
      }
    ],
    "domains": [
      "utc.edu",
      "discord.gg",
      "wa.exe"
    ],
    "ip_addresses": []
  },
  "derived_flags": {
    "display_name_mismatch": false,
    "sender_domain_mismatch": false,
    "lookalike_domain_detected": false,
    "internal_impersonation": false,
    "unicode_trick_detected": false
  },
  "keyword_counts": {
    "urgency": 0,
    "credentials": 0,
    "payment": 0,
    "threat": 0
  },
  "label": null
}
